name: Update Lambdas

on:
  push:
    branches: [ main ]
    paths:
      - 'lambdas/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'lambdas/**'
      - 'package.json'
      - 'package-lock.json'

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '20'
  CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
  CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  PRODUCTS_TABLE: ${{ secrets.PRODUCTS_TABLE }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
  update-lambdas:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Update Lambdas
        run: |
          npm run build
          npx cdk deploy --require-approval never --no-notices --exclusively ApiStack --app "npx ts-node --prefer-ts-exts cdk/bin/deploy.ts" 